stages:
  - build

variables:
  image_name: jitesoft/youtrack

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo ${CI_JOB_TOKEN} | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
  script:
    - docker build --label "youtrack.version=${CI_COMMIT_TAG}" --build-arg VERSION=${CI_COMMIT_TAG} -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} .
    - TAGS="latest ${CI_COMMIT_TAG} ${CI_COMMIT_TAG:0:6} ${CI_COMMIT_TAG:0:8}"
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
    - docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}:latest
    - docker push ${CI_REGISTRY_IMAGE}:latest
    - for tag in $TAGS; do docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${image_name}:${tag}; docker push ${image_name}:${tag}; done
  only:
    refs:
      - tags
  tags:
    - jitesoft
