stages:
  - build

variables:
  image_name: jitesoft/youtrack

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USER} --password-stdin
  script:
    - docker build --build-arg YOUTRACK_VERSION=${CI_COMMIT_TAG} -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} .
    - TAGS="latest ${CI_COMMIT_TAG} ${CI_COMMIT_TAG:0:6} ${CI_COMMIT_TAG:0:8}"
    - for tag in $TAGS; do docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${image_name}:${tag}; docker push ${image_name}:${tag}; done
  only:
    refs:
      - tags